[project]
name = "labs"
version = "0.1.0"
description = "lab1 M3"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.2",
]

[[tool.mypy.overrides]]
module = [
    "pytest",
    "pytest.*"
]
ignore_missing_imports = true
